version: "3.9"

networks:
  ecomerce-network:
    driver: bridge

services:

  ecomerce-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Ed.183729"
    ports:
      - "3307:3306"
    networks:
      - "ecomerce-network"


  ecomerce-auth:
    build: ./auth/demo/demo
    image: ecomerce-auth
    environment:
      DB_HOST: ecomerce-mysql
      PROFILE: docker
    ports:
      - "8080:8080"
    networks:
      - ecomerce-network
    depends_on:
      - ecomerce-mysql

  ecomerce-proxy:
    build: .
    image: ecomerce-proxy
    ports:
      - "80:80"
    networks:
      - ecomerce-network
    depends_on:
      - ecomerce-auth
    