version: "3.9"

networks:
  ecomerce-network:
    drivar: bridge

service:

  ecomerce-mysql:
    image: mysql
  enviroment:
    MYSQL_ROOT_PASSWORD: "Ed.183729"
  ports:
    - "3306:3306"
  networks:
    - "ecomerce-network"


  ecomerce-auth:
    buid: ./auth/demo/demo
    image: ecomerce-auth
    enviroment:
      DB_HOST: ecomerce-mysql
      PROFILE: docker
    ports:
      - "8080:8080"
    