server {
  listen 80;

  # endpoints públicos do Authorization Server
  location /oauth2/ {
    proxy_pass http://ecomerce-auth:8080;
  }

  location /auth/register {
    proxy_pass http://ecomerce-auth:8080/auth/register;
    proxy_set_header Host $host;
    #proxy_pass http://host.docker.internal:8080/auth/login;
  
  }

  location /auth/login {
    proxy_pass http://ecomerce-auth:8080/auth/login;
    #proxy_pass http://host.docker.internal:8080/auth/login;
    proxy_set_header Host $host;
  }

  location /auth/callback {
    proxy_pass http://ecomerce-auth:8080;
  }

  # validação interna — só o Nginx chama
  location = /auth/validate {
    internal;
    proxy_pass http://ecomerce-auth:8080/auth/validate;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Cookie $http_cookie;
  }

  # rotas privadas
  # location /carrinho {
  #   auth_request /auth/validate; 
  #   proxy_pass http://cart-service:8081; 
  #   proxy_set_header Cookie $http_cookie;
  # }

  # location /ordem {
  #   auth_request /auth/validate;
  #   proxy_pass http://order-service:8082;
  # }

  # location /pagamento {
  #   auth_request /auth/validate;
  #   proxy_pass http://payment-service:8083;
  # }

  #rota pública
  location /produto {
    # nome da imagem
    proxy_pass http://ecomerce-produto:8081;
  }
}