spring.application.name=demo

server.port=8080
#setx PROFILE "qas"
spring.profiles.active=${PROFILE}


security.jwt.private-key-path=C:/keys/private.pem
security.jwt.public-key-path=C:/keys/public.pem

spring.datasource.url=jdbc:mysql://localhost:3306/dbcliente?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ed.183729

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.ssl.enabled=false