#flyway.url=jdbc:mysql://localhost:3306/authmicro?createDatabaseIfNotExist=true&serverTimezone=UTC

flyway.url=jdbc:mysql://${DB_HOST:localhost}/authmicro?createDatabaseIfNotExist=true&serverTimezone=UTC
flyway.user=root
flyway.password=Ed.183729