spring.application.name=demo

server.port=8081



spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}/dbProduto?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ed.183729

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
algafood.storage.local.diretorio-fotos = C:/Users/Edilson/Desktop/catalogo/

